# Generated by Django 4.0.5 on 2022-06-15 00:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_city', models.CharField(help_text='Miasto', max_length=30)),
                ('name_of_street', models.CharField(help_text='Ulica', max_length=30)),
                ('market', models.CharField(choices=[('WTÓRNY', 'wtórny'), ('PIERWOTNY', 'pierwotny')], help_text='Rynek', max_length=30)),
                ('floor_area', models.IntegerField(help_text='m2', validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(1)])),
                ('how_many_rooms', models.IntegerField(help_text='Ilość pokoi', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('how_many_levels', models.IntegerField(help_text='Ile pięter w mieszkaniu?', validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('price', models.IntegerField(help_text='Cena', validators=[django.core.validators.MaxValueValidator(20000000), django.core.validators.MinValueValidator(1)])),
                ('which_flor', models.IntegerField(help_text='Piętro w budynku', validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(1)])),
                ('how_many_flors', models.IntegerField(help_text='Ile pięter w budynku?', validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(1)])),
                ('flat_condition', models.CharField(choices=[('PO_REMONCIE', 'po remoncie'), ('DOBRY', 'dobry'), ('DO_REMONTU', 'do remontu')], help_text='Stan mieszkania', max_length=30)),
                ('how_high', models.IntegerField(help_text='Wysokość w cm', validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(1)])),
                ('flat_facilities', models.CharField(choices=[('WINDA', 'winda'), ('PODJAZD NA WÓZKI', 'podjazd na wózki'), ('WINDA DLA WÓZKÓW', 'winda dla wózków')], help_text='Udogodnienia', max_length=30)),
                ('why_flat_change', models.CharField(choices=[('ZMIANA MIASTA', 'zmiana miasta'), ('ZMIANA NA WIĘKSZE', 'zmiana na większe'), ('INNE', 'inne')], help_text='Powód zmiany nieruchomości', max_length=30)),
                ('type_of_building', models.CharField(choices=[('BD', 'BD')], help_text='Rodzaj budynku', max_length=30)),
                ('around_facilities', models.CharField(choices=[('BD', 'BD')], help_text='Udogodnienia w budynku', max_length=30)),
                ('around_security', models.CharField(choices=[('BD', 'BD')], help_text='Bezpieczeństwo okolicy', max_length=30)),
                ('building_condition', models.CharField(choices=[('BD', 'BD')], help_text='Stan budynku', max_length=30)),
            ],
        ),
    ]
