# Generated by Django 4.0.5 on 2022-06-22 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0002_quest_around_facilities_quest_around_security_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrage', models.PositiveIntegerField(help_text='w metrach kwadratowych', verbose_name='metraż')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='quest.quest')),
            ],
        ),
    ]
