# Generated by Django 4.0.5 on 2022-06-22 19:27

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0003_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='how_many_levels',
        ),
        migrations.AddField(
            model_name='quest',
            name='number_of_building',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(1)], verbose_name='Numer budynku'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quest',
            name='flat_facilities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('WINDA', 'winda'), ('PODJAZD NA WÓZKI', 'podjazd na wózki'), ('WINDA DLA WÓZKÓW', 'winda dla wózków')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='how_many_rooms',
            field=models.IntegerField(help_text='Ilość pokoi', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Liczba pokoi'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='name_of_city',
            field=models.CharField(max_length=50, verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='name_of_street',
            field=models.CharField(max_length=30, verbose_name='Nazwa ulicy'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='price',
            field=models.IntegerField(help_text='PLN', validators=[django.core.validators.MaxValueValidator(20000000), django.core.validators.MinValueValidator(1)]),
        ),
    ]
