# Generated by Django 4.0.5 on 2022-06-23 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0005_remove_quest_around_facilities_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quest',
            old_name='how_many_flors',
            new_name='how_many_floors',
        ),
        migrations.RenameField(
            model_name='quest',
            old_name='which_flor',
            new_name='which_floor',
        ),
        migrations.AlterField(
            model_name='quest',
            name='atribute1',
            field=models.CharField(choices=[('przestronne', 'przestronne'), ('przytulne', 'przytulne'), ('funkcjonalne', 'funkcjonalne'), ('rozkładowe', 'rozkładowe '), ('słoneczne', 'sloneczne'), ('zaciszne', 'zaciszne'), ('dobrze zlokalizowane', 'dobrze zlokalizowane'), ('bezpieczne', 'bezpieczne'), ('duże', 'duże'), ('nowoczesne', 'nowoczesne'), ('tradycyjne', 'tradycyjne'), ('wyremontowane', 'wyremontowane'), ('świetnie skomunikowane', 'świetnie skomunikowane'), ('w otoczeniu zieleni', 'w otoczeniu zieleni'), ('ustawne', 'ustawne'), ('z pełną infrastrukturą usługowo-handlową', 'z pełną infrastrukturą usługowo-handlową'), ('wielofunkcyjne ', 'wielofunkcyjne'), ('prestiżowe ', 'prestiżowe'), ('wyjątkowe ', 'wyjątkowe'), ('współczesne ', 'współczesne'), ('postmodernistyczne ', 'postmodernistyczne'), ('rozbudowane ', 'rozbudowane'), ('rekreacyjne ', 'rekreacyjne'), ('stylowe', 'stylowe'), ('niepowtarzalne', 'niepowtarzalne'), ('rozwinięte ', 'rozwinięte'), ('bezpośrednie', 'bezpośrednie'), ('unikalne', 'unikalne'), ('niepowtarzalne', 'niepowtarzalne'), ('eleganckie', 'eleganckie'), ('ekskluzywne', 'ekskluzywne')], max_length=130, null=True, verbose_name='Cecha 1'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='atribute2',
            field=models.CharField(choices=[('przestronne', 'przestronne'), ('przytulne', 'przytulne'), ('funkcjonalne', 'funkcjonalne'), ('rozkładowe', 'rozkładowe '), ('słoneczne', 'sloneczne'), ('zaciszne', 'zaciszne'), ('dobrze zlokalizowane', 'dobrze zlokalizowane'), ('bezpieczne', 'bezpieczne'), ('duże', 'duże'), ('nowoczesne', 'nowoczesne'), ('tradycyjne', 'tradycyjne'), ('wyremontowane', 'wyremontowane'), ('świetnie skomunikowane', 'świetnie skomunikowane'), ('w otoczeniu zieleni', 'w otoczeniu zieleni'), ('ustawne', 'ustawne'), ('z pełną infrastrukturą usługowo-handlową', 'z pełną infrastrukturą usługowo-handlową'), ('wielofunkcyjne ', 'wielofunkcyjne'), ('prestiżowe ', 'prestiżowe'), ('wyjątkowe ', 'wyjątkowe'), ('współczesne ', 'współczesne'), ('postmodernistyczne ', 'postmodernistyczne'), ('rozbudowane ', 'rozbudowane'), ('rekreacyjne ', 'rekreacyjne'), ('stylowe', 'stylowe'), ('niepowtarzalne', 'niepowtarzalne'), ('rozwinięte ', 'rozwinięte'), ('bezpośrednie', 'bezpośrednie'), ('unikalne', 'unikalne'), ('niepowtarzalne', 'niepowtarzalne'), ('eleganckie', 'eleganckie'), ('ekskluzywne', 'ekskluzywne')], max_length=130, null=True, verbose_name='Cecha 2'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='atribute3',
            field=models.CharField(choices=[('przestronne', 'przestronne'), ('przytulne', 'przytulne'), ('funkcjonalne', 'funkcjonalne'), ('rozkładowe', 'rozkładowe '), ('słoneczne', 'sloneczne'), ('zaciszne', 'zaciszne'), ('dobrze zlokalizowane', 'dobrze zlokalizowane'), ('bezpieczne', 'bezpieczne'), ('duże', 'duże'), ('nowoczesne', 'nowoczesne'), ('tradycyjne', 'tradycyjne'), ('wyremontowane', 'wyremontowane'), ('świetnie skomunikowane', 'świetnie skomunikowane'), ('w otoczeniu zieleni', 'w otoczeniu zieleni'), ('ustawne', 'ustawne'), ('z pełną infrastrukturą usługowo-handlową', 'z pełną infrastrukturą usługowo-handlową'), ('wielofunkcyjne ', 'wielofunkcyjne'), ('prestiżowe ', 'prestiżowe'), ('wyjątkowe ', 'wyjątkowe'), ('współczesne ', 'współczesne'), ('postmodernistyczne ', 'postmodernistyczne'), ('rozbudowane ', 'rozbudowane'), ('rekreacyjne ', 'rekreacyjne'), ('stylowe', 'stylowe'), ('niepowtarzalne', 'niepowtarzalne'), ('rozwinięte ', 'rozwinięte'), ('bezpośrednie', 'bezpośrednie'), ('unikalne', 'unikalne'), ('niepowtarzalne', 'niepowtarzalne'), ('eleganckie', 'eleganckie'), ('ekskluzywne', 'ekskluzywne')], max_length=130, null=True, verbose_name='Cecha 3'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='floor_area',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(1)], verbose_name='Powierzchnia (m2)'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='parking',
            field=models.CharField(choices=[('miejsce w garażu podziemnym', 'miejsce w garażu podziemnym'), ('miejsce w garażu naziemnym', 'miejsce w garażu naziemnym'), ('parking na ulicy', 'parking na ulicy'), ('nie przynależy', 'nie przynależy')], max_length=30, null=True, verbose_name='Parking'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='type_of_building',
            field=models.CharField(choices=[('kamienicy', 'kamienicy'), ('bloku', 'bloku'), ('szeregowcu', 'szeregowcu')], max_length=30, null=True, verbose_name='Rodzaj budynku'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='when_move_out',
            field=models.CharField(choices=[('kilka tygodni', 'za kilka tygodni'), ('około miesiąc', 'za około miesiąc')], max_length=30, null=True, verbose_name='Wolne od'),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor_area',
            field=models.PositiveIntegerField(verbose_name='metraż'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_additional_space',
            field=models.CharField(choices=[('brak', 'brak'), ('taras', 'taras'), ('ogródek', 'ogródek'), ('balkon', 'balkon'), ('loggia', 'loggia')], max_length=70, null=True, verbose_name='Powierzchnie przynależne'),
        ),
        migrations.AlterField(
            model_name='room',
            name='type_of_room',
            field=models.CharField(choices=[('salon', 'salon'), ('salon z aneksem', 'salon z aneksem'), ('pokoj', 'pokój'), ('korytarz', 'korytarz'), ('lazienka', 'lazienka'), ('toaleta', 'wc'), ('łazienka z wc', 'lazienka z wc'), ('garderoba', 'garderoba'), ('pomieszczenie gospodarcze', 'pomieszczenie gospodarcze')], max_length=70, null=True, verbose_name='Rodzaj pomieszczenia'),
        ),
        migrations.AlterField(
            model_name='room',
            name='window_in_room',
            field=models.CharField(choices=[('tak', (('okna na północ', 'na północ'), ('okna na wschód', 'na wschód'), ('okna na południe', 'na południe'), ('okna na zachód', 'na zachód'))), ('nie', (('bez okien', 'bez okien'),))], max_length=70, null=True, verbose_name='Ekspozycja okien'),
        ),
    ]
